import type { Exercise } from "./types";

export const SAMPLE_EXERCISES: Exercise[] = [
	{
		id: "bench-press",
		name: "Bench Press",
		equipment: ["Flat Bench", "Barbell"],
		muscles: ["Chest", "Triceps"],
		instructions: [
			"Lie flat on the bench",
			"Grip barbell slightly wider than shoulder width",
			"Press feet firmly into the ground",
			"Keep your core engaged",
			"Slowly lift the bar off the rack",
			"Lower the barbell down slowly to nipple level",
			"Stop lowering when elbows are just below the bench",
			"Push the bar up to the floor as you push the bar back up",
		],
		notes: "Use a spotter, if unable, consider Dumbbell Bench Press",
	},
	{
		id: "barbell-squat",
		name: "Barbell Squat",
		equipment: ["Barbell", "Squat Rack"],
		muscles: ["Quadriceps", "Glutes", "Hamstrings"],
		instructions: [
			"Position barbell on upper back",
			"Stand with feet shoulder-width apart",
			"Keep chest up and core tight",
			"Lower down by bending knees and hips",
			"Descend until thighs are parallel to ground",
			"Push through heels to return to start",
			"Keep knees tracking over toes",
		],
		notes: "Start with lighter weight to master form. Consider using a safety rack.",
	},
	{
		id: "pullup",
		name: "Pull-up",
		equipment: ["Pull-up Bar"],
		muscles: ["Lats", "Biceps", "Upper Back"],
		instructions: [
			"Grip pull-up bar with palms facing away",
			"Hang with arms fully extended",
			"Engage core and squeeze shoulder blades",
			"Pull yourself up until chin clears bar",
			"Lower yourself with control",
			"Avoid swinging or kipping",
		],
		notes: "Use resistance bands for assistance if needed. Progress gradually.",
	},
	{
		id: "dumbbell-curl",
		name: "Dumbbell Curl",
		equipment: ["Dumbbells"],
		muscles: ["Biceps"],
		instructions: [
			"Stand with feet shoulder-width apart",
			"Hold dumbbells at sides with palms forward",
			"Keep elbows close to torso",
			"Curl weights up toward shoulders",
			"Squeeze biceps at the top",
			"Lower dumbbells with control",
			"Avoid swinging or using momentum",
		],
		notes: "Focus on form over weight. Keep wrists straight throughout movement.",
	},
	{
		id: "overhead-press",
		name: "Overhead Press",
		equipment: ["Barbell"],
		muscles: ["Shoulders", "Triceps"],
		instructions: [
			"Stand with feet shoulder-width apart",
			"Hold barbell at shoulder height",
			"Grip slightly wider than shoulders",
			"Press bar straight up overhead",
			"Lock out arms at the top",
			"Lower bar back to shoulders with control",
		],
		notes: "Keep core tight to protect lower back. Don't arch excessively.",
	},
	{
		id: "deadlift",
		name: "Deadlift",
		equipment: ["Barbell"],
		muscles: ["Back", "Glutes", "Hamstrings", "Quadriceps", "Traps"],
		instructions: [
			"Stand with feet hip-width apart",
			"Bend at hips and knees to grip bar",
			"Keep back straight and chest up",
			"Drive through heels to stand up",
			"Squeeze glutes at the top",
			"Lower bar with control",
		],
		notes: "Master form with light weight first. This is a complex movement.",
	},
	{
		id: "pushup",
		name: "Push-up",
		equipment: ["No Equipment"],
		muscles: ["Chest", "Triceps", "Shoulders"],
		instructions: [
			"Start in a plank position with hands shoulder-width apart",
			"Keep body in a straight line from head to heels",
			"Engage your core throughout the movement",
			"Lower your body until chest nearly touches the floor",
			"Keep elbows at about 45-degree angle",
			"Push back up to starting position",
			"Maintain straight body alignment throughout",
		],
		notes: "Modify by doing knee push-ups if needed. Focus on quality over quantity.",
	},
	{
		id: "situp",
		name: "Sit-up",
		equipment: ["No Equipment"],
		muscles: ["Abs", "Hip Flexors"],
		instructions: [
			"Lie on your back with knees bent and feet flat",
			"Place hands behind your head or crossed on chest",
			"Engage your core muscles",
			"Curl your upper body up toward your knees",
			"Lift shoulder blades off the ground",
			"Lower back down with control",
			"Keep your feet anchored throughout",
		],
		notes: "Avoid pulling on your neck. Focus on using abdominal muscles.",
	},
	{
		id: "dumbbell-row",
		name: "Dumbbell Row",
		equipment: ["Dumbbells", "Bench"],
		muscles: ["Lats", "Rhomboids", "Biceps"],
		instructions: [
			"Place one knee and hand on bench",
			"Hold dumbbell in opposite hand",
			"Keep back parallel to ground",
			"Pull dumbbell up to ribcage",
			"Squeeze shoulder blade at top",
			"Lower with control",
		],
		notes: "Avoid rotating torso. Keep core engaged throughout.",
	},
	{
		id: "leg-press",
		name: "Leg Press",
		equipment: ["Leg Press Machine"],
		muscles: ["Quadriceps", "Glutes"],
		instructions: [
			"Sit in leg press machine",
			"Place feet shoulder-width on platform",
			"Release safety handles",
			"Lower platform by bending knees",
			"Stop when knees reach 90 degrees",
			"Push through heels to extend legs",
		],
		notes: "Don't lock out knees completely at top. Keep lower back pressed against pad.",
	},
	{
		id: "lateral-raise",
		name: "Lateral Raise",
		equipment: ["Dumbbells"],
		muscles: ["Shoulders"],
		instructions: [
			"Stand with feet shoulder-width apart",
			"Hold dumbbells at sides",
			"Keep slight bend in elbows",
			"Raise arms out to sides",
			"Stop when arms reach shoulder height",
			"Lower with control",
		],
		notes: "Use lighter weight than you think. Focus on shoulder isolation.",
	},
	{
		id: "tricep-dip",
		name: "Tricep Dip",
		equipment: ["Dip Bars"],
		muscles: ["Triceps", "Chest"],
		instructions: [
			"Grip parallel bars and lift yourself up",
			"Start with arms fully extended",
			"Lean slightly forward",
			"Lower body by bending elbows",
			"Stop when elbows reach 90 degrees",
			"Push back up to starting position",
		],
		notes: "Keep shoulders down and back. Use assistance machine if needed.",
	},
];

export const ALL_EQUIPMENT = [
	"Barbell",
	"Dumbbells",
	"Flat Bench",
	"Pull-up Bar",
	"Squat Rack",
	"Leg Press Machine",
	"Dip Bars",
] as const;

